Feature/home page： 完成首頁切版
LandyHsiao/beauty-hub pull request #29
Opened 2023-08-23 17:31 UTC by LandyHsiao

2023-08-24 02:18 UTC, ann328 commented on pages/index.html
> +          <div class="home-banner__carousel-1 carousel-item active h-100 pt-27 pb-7 py-md-60">
在平板的時候，好像沒有成比例縮小，因此會看不到設計稿上的化妝品圖案

2023-08-24 03:14 UTC, LandyHsiao commented on pages/index.html
> +          <div class="home-banner__carousel-1 carousel-item active h-100 pt-27 pb-7 py-md-60">
因為我是設定bg-size:cover跟bg-position:center啦，所以縮放行為是對的[(code在這裡)](https://github.com/LandyHsiao/beauty-hub/blob/93b414ffd72c9131fe0d4082d7b071e998900f87/assets/scss/pages/_index.scss#L25)
要達成讓圖裡的化妝品出現，就不能用bg-position:center，會變成這樣↓
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/5500a199-e050-4a7a-a3e9-fe866ffa6f91)
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/4797809a-4ae8-4087-80f3-7d6189ac2fce)
文字會疊在物件上妨礙閱讀，所以我認為圖片不該出現才是對的

2023-08-24 04:30 UTC, ann328 requested changes
2.詳細分類好搜索　這裡的背景在平板的時候沒有按比例縮小，因此會看不到設計稿上圖片上的化妝品，會被裁切掉
3.詳細分類好搜索　這裡的padding在電腦設計稿顯示36px，但是實際呈現畫面為48px
4.現在註冊，享受完整功能　這裡按鈕在電腦和手機的font-weight設計稿顯示500，實際呈現畫面為400
5.好評推推　的標題在電腦font-weight設計稿顯示500，手機顯示600，實際呈現畫面為400 
6.好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px 
7.BEAUTY  AWARDS 2023　的padding在電腦padding-top設計稿顯示12px，實際呈現畫面為16px
8.BEAUTY  AWARDS 2023　的BEAUTY&AWARDS下方的padding在電腦設計稿顯示36px，實際呈現畫面為48px
9.BEAUTY  AWARDS 2023　的2023下方的padding在手機設計稿是對其旁邊的按鈕，實際呈現畫面有12px
10.9.BEAUTY  AWARDS 2023　的查看全部電腦和手機font-weight設計稿顯示500，實際呈現畫面為400
11.HOT ISSUE　的標題電腦font-weight設計稿顯示700，實際呈現畫面為500
12.HOT ISSUE　的內文電腦font-size設計稿顯示20px，font-weight設計稿顯示500，實際呈現畫面為16px 400
13.HOT ISSUE　的看更多電腦font-weight設計稿顯示500，實際呈現畫面為400
14.footer　在平板觀看關於我們、聯絡我們顯得太壅擠
15.footer　右邊logo在手機板的大小跟設計搞不太一樣
16.footer　的標題在手機font-size設計稿顯示16px，實際呈現畫面為20px

letter-spacing：
1.熱門排行　的標題
2.熱門排行　的tab
3.熱門排行　的右上角名次
4.熱門排行　的產品名稱
5.熱門排行　的品牌名稱
6.詳細分類好搜索　的內文
7.好評推推　的標題
8.好評推推　的產品名稱
9.HOT ISSUE　的標題
10.HOT ISSUE　的內文
11.footer　的標題和內文

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +          <div class="home-banner__carousel-2 carousel-item h-100 pt-27 pb-7 py-md-60">
banner 在平板的時候沒有按比例縮小，因此會看不到設計稿上圖片上的一些化妝品，會變成有點單一純色的畫面，有些化妝品or用具圖示也會被裁切

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +          <div class="home-banner__carousel-3 carousel-item h-100 pt-27 pb-7 py-md-60">
banner 在平板的時候沒有按比例縮小，因此會看不到設計稿上圖片上的一些化妝品，會變成有點單一純色的畫面，有些化妝品or用具圖示也會被裁切

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +      <h2 class="h6 fs-sm-4 fs-md-3 mb-6 mb-md-12 text-md-center ls-p">好評推推</h2>
好評推推　的標題在電腦font-weight設計稿顯示500，手機顯示600，實際呈現畫面為400

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
好評推推　的評論內容白色背景在電腦padding-y設計稿顯示16px，實際呈現畫面為4px

2023-08-24 04:30 UTC, ann328 commented on pages/index.html
> +          <div class="home-banner__carousel-1 carousel-item active h-100 pt-27 pb-7 py-md-60">
原來如此！結案！

2023-08-24 04:42 UTC, LandyHsiao commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/b1878bf6-8999-4227-b351-05ab5cb4434a)
自多的時候可以看出來是4px，16px是字少的時候垂直致中產生的

2023-08-24 04:44 UTC, LandyHsiao commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
同上「字多的時候可以看出來是4px，16px是字少的時候垂直置中產生的」

2023-08-24 04:44 UTC, LandyHsiao commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
同上「字多的時候可以看出來是4px，16px是字少的時候垂直置中產生的」

2023-08-24 04:44 UTC, LandyHsiao commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
同上「字多的時候可以看出來是4px，16px是字少的時候垂直置中產生的」

2023-08-24 04:44 UTC, LandyHsiao commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
同上「字多的時候可以看出來是4px，16px是字少的時候垂直置中產生的」

2023-08-24 04:47 UTC, ann328 commented on pages/index.html
> +                  <div class="card-text review-card__content text-start fs-7 fs-md-6 text-Gray-02 ls-h bg-white py-4 py-md-1 px-3 align-middle flex-grow-1 w-100 overflow-hidden d-flex flex-column jus
原來如此！結案！

2023-08-25 14:37 UTC, ann328 requested changes
1.BEAUTY AWARDS 2023 查看更多的按鈕的電腦手機設計稿為500，實際呈現畫面為400
BEAUTY AWARDS 2023 標題（應該是標題？）手機設計稿letter-spacing為0.84px，實際呈現畫面為1.4px
2.HOT ISSUE 的內容light-height電腦設計稿為24px，實際呈現畫面為30px
HOT ISSUE 的第三個card內容（韓星都在畫..）手機設計稿letter-spacing為0.8px，實際呈現畫面為0.48px
3.熱門排行 標題手機設計稿font-size為20px、font-weight為600、line-height為24px、letter-spacing為0.6px，實際畫面為ont-size為16px、font-weight為500、line-height為19.2px、letter-spacing為0.48px
4.熱門排行 品牌標題手機設計稿letter-spacing為0.36px，實際呈現畫面為0.6px
5.好評推推 標題手機設計稿font-size為20px、fline-height為24px、letter-spacing為0.6px，實際畫面為ont-size為16px、line-height為19.2px、letter-spacing為0.48px
6.好評推推 內文手機設計稿letter-spacing為0.7px，實際呈現畫面為0.42

2023-08-25 14:37 UTC, ann328 commented on pages/index.html
> +                  <h3 class="home-banner__subtitle display-2 fw-bold text-Gray-07 mb-md-4">Search<br class="d-md-none"> &<br class="d-md-none"> Share!</h3>
這裡的letter-spacing電腦跟手機呈現畫面是0.8px，設計稿電腦是2.2px，手機是1.6px

2023-08-25 14:37 UTC, ann328 commented on pages/index.html
> +                  <h2 class="home-banner__title d-none d-md-block display-2 fw-bold fs-md-1 mb-md-8">讓 BeautyHub 成為你的美妝百科</h2>
這裡的letter-spacing呈現畫面電腦是0.8px，手機是0.48px，設計稿電腦是2px，手機是0.72px

2023-08-25 15:36 UTC, ann328 approved these changes

2023-08-25 15:36 UTC, merged