Feature/product：完成產品頁切版
LandyHsiao/beauty-hub pull request #42
Opened 2023-08-31 15:55 UTC by LandyHsiao

1. 線稿圖中此部分沒有做，因為我覺得產品頁重要的標題是產品名字，放個分類在上面很醜又沒用
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/b864e256-12ff-4a98-9693-3e51f5c31836)
2.  評論tab的pagination目前先放default樣式，等之後另外開branch覆蓋pagination變數之後就好了
3. 目前此頁面以熱門排行第一個產品當作內容參考來源，與線稿圖不同，是考量到這大概是首頁上第一個會被點擊的產品頁面。其餘產品頁面的製作會在本次PR通過後進行量產
4. PC版上我在產品名稱下方新增了一個tag區塊免得太空，這部分線稿圖沒有。
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/cf3653b4-dbae-4268-a668-fc996ca20867)

2023-09-01 10:13 UTC, cestJessie requested changes

2023-09-01 10:13 UTC, jccodeob1o commented on assets/image/user-prifile.jpg
應該是user-profile?

2023-09-01 10:13 UTC, jccodeob1o commented on pages/product_01.html
> +      <div class="col-12 col-md-12 col-lg-10 col-xxl-10 mx-auto">
col-12 col-md-12、col-lg-10 col-xxl-10 皆2擇1即可

2023-09-01 10:13 UTC, jccodeob1o commented on pages/product_01.html
> +                  <p class="chemical-list__link-out fs-7 fs-sm-6 mb-0 w-sm-10 align-top px-sm-2 text-center d-flex justify-content-end justify-content-sm-center">
fs-sm-6應該是多的

2023-09-01 16:13 UTC, LandyHsiao commented on pages/product_01.html
> +                  <p class="chemical-list__link-out fs-7 fs-sm-6 mb-0 w-sm-10 align-top px-sm-2 text-center d-flex justify-content-end justify-content-sm-center">
不是多的，沒寫這行字體大小就會永遠是14px喔

2023-09-03 04:36 UTC, cestJessie approved these changes

2023-09-03 04:38 UTC, merged