feat: about_b-hub
LandyHsiao/beauty-hub pull request #43
Opened 2023-09-01 07:10 UTC by cestJessie

新增一個about_b-hub.html

2023-09-01 15:52 UTC, LandyHsiao requested changes
似乎發PR前你沒有把develop merge進來過喔？
作為練習，請在修改後試著把最新版的develop merge進來，嘗試在local上解衝突再push上來

2023-09-01 15:52 UTC, LandyHsiao commented on pages/about_b-hub.html
> +          <li class="breadcrumb-item active" aria-current="page">網站理念</li>
目前這個不會跟著tab切換改變的話，不如拿掉，到關於我們為止就好?

2023-09-01 15:52 UTC, LandyHsiao commented on pages/about_b-hub.html
> +        <div class="tab-content col-md-7" id="v-pills-tabContent">
mobile layout可以做滿版的col-12，不然很壅擠
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/7fe80749-a00a-4281-84e8-dc8d8b061116)

2023-09-01 15:52 UTC, LandyHsiao commented on pages/about_b-hub.html
> +        <div class="nav flex-column nav-pills align-items-center col-md-3 col-12 pe-0 mb-md-0 mb-4" id="v-pills-tab" role="tablist"
1. 建議md以上時把tabs固定頂端?不然隨著viewport縮小tab幾乎跑到畫面最下方了
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/d8e3d64b-3f3a-4c9b-931d-8572eb80cd8d)
2.  空間允許的情況下要不要考慮把md以下的tabs改成水平排列
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/40004121-8d93-4fee-a103-8bfe25d6037b)

2023-09-01 15:52 UTC, LandyHsiao commented on pages/about_b-hub.html
> +        <div class="nav flex-column nav-pills align-items-center col-md-3 col-12 pe-0 mb-md-0 mb-4" id="v-pills-tab" role="tablist"
上述意見是因為我覺得UX很糟而建議的，如果你覺得沒問題就不用改了

2023-09-01 15:52 UTC, LandyHsiao commented on pages/about_b-hub.html
md ~ lg時文字區塊太壅擠，給間隔留白的空間太多了
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/dbe4194a-9d31-4519-973d-16a007a15b28)

2023-09-01 16:17 UTC, LandyHsiao commented on pages/about_b-hub.html
> +          <li class="breadcrumb-item active" aria-current="page">網站理念</li>
更新：我的用詞不夠精確，我的意思是目前麵包屑似乎是固定在「網站理念」這裡，但顯然關於我們有四個tab可以切換
我認為要嘛這裡會隨著tab切換改，要不就寫到關於我們為止就好？

2023-09-03 05:14 UTC, cestJessie commented on pages/about_b-hub.html
> +          <li class="breadcrumb-item active" aria-current="page">網站理念</li>
可以～當初是擔心頁面太空所以才做了其他頁面

2023-09-03 05:19 UTC, cestJessie commented on pages/about_b-hub.html
> +          <li class="breadcrumb-item active" aria-current="page">網站理念</li>
已註解掉<li class="breadcrumb-item active" aria-current="page">網站理念</li>

2023-09-03 05:25 UTC, cestJessie commented on pages/about_b-hub.html
> +        <div class="tab-content col-md-7" id="v-pills-tabContent">
已修改

2023-09-03 09:39 UTC, cestJessie commented on pages/about_b-hub.html
> +        <div class="nav flex-column nav-pills align-items-center col-md-3 col-12 pe-0 mb-md-0 mb-4" id="v-pills-tab" role="tablist"
已修改

2023-09-03 09:39 UTC, cestJessie commented on pages/about_b-hub.html
已修改

2023-09-03 13:06 UTC, LandyHsiao requested changes

2023-09-03 13:06 UTC, LandyHsiao commented on assets/scss/pages/_about_b-hub.scss
> +  outline: 1px solid red;
忘記拿掉囉

2023-09-03 13:06 UTC, LandyHsiao commented on pages/about_b-hub.html
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/f1e212fb-3d8b-4f69-8d7b-9867111be32d)
好像還是一樣寬

2023-09-04 13:16 UTC, LandyHsiao requested changes

2023-09-04 13:16 UTC, LandyHsiao commented on assets/scss/all.scss
> +@import "pages/_member_register";
重複了

2023-09-04 13:16 UTC, LandyHsiao commented on assets/scss/utils/_map.scss
spacing的map一堆值不見了所以其他頁面才會壞掉

2023-09-04 14:20 UTC, LandyHsiao approved these changes

2023-09-04 14:20 UTC, merged