Feature/search
LandyHsiao/beauty-hub pull request #48
Opened 2023-09-01 15:51 UTC by ann328

add search page

2023-09-01 16:07 UTC, LandyHsiao requested changes

2023-09-01 16:07 UTC, LandyHsiao commented on pages/search.html
> +                    <div class="py-md-9 ps-md-6 py-15 ps-5 mb-md-0 mb-4">
lg以下請把ps拿掉，否則如圖，視覺上寬度沒有滿版
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/e4d97aff-fe97-4c8b-add1-ba11ae07afd8)

2023-09-01 16:07 UTC, LandyHsiao commented on pages/search.html
> +                            <ol class="list-unstyled d-flex">
列表中所有hover效果建議加上一定數值的`text-underline-offset`比較好看
此建議出於我個人美觀考量，請自行考量是否要修改。

2023-09-01 16:33 UTC, ann328 commented on pages/search.html
> +                            <ol class="list-unstyled d-flex">
好的，改～

2023-09-01 16:35 UTC, ann328 commented on pages/search.html
> +                    <div class="py-md-9 ps-md-6 py-15 ps-5 mb-md-0 mb-4">
抱歉，我沒注意到！

2023-09-02 06:44 UTC, LandyHsiao approved these changes

2023-09-02 06:44 UTC, merged