Feature/beauty awards
LandyHsiao/beauty-hub pull request #51
Opened 2023-09-03 05:07 UTC by cestJessie

新增beauty＿awards

2023-09-03 11:47 UTC, LandyHsiao requested changes

2023-09-03 11:47 UTC, LandyHsiao commented on assets/image/beauty-awards/2023SS.png
這圖左右兩邊空白長度不一樣喔，放在網頁上一就知道到沒有置中

2023-09-03 11:47 UTC, LandyHsiao commented on assets/scss/pages/_beauty_awards.scss
> +  color: $gradient-02;
這顏色太淺跟背景色對比有點低，色弱應該會看不到字喔

2023-09-03 11:47 UTC, LandyHsiao commented on pages/beauty_awards.html
出於統一性我會建議產品卡片都要長差不多
目前長完全不一樣是有另外的考量嗎？
目前我是猜想你認為Beauty Awards是特殊的版面想要有不一樣的設計？

2023-09-03 11:47 UTC, LandyHsiao commented on pages/beauty_awards.html
> +            <p class="lh-base mb-0 text-justify flex-grow-1 text-Gray-01 link-Gray-02 fs-md-6 fs-7">皇家蜂王乳雙導精華</p>
不是heading element或是heading class的話本來就是預設是line-height-base的1.5，所以lh-base是多的要拿掉

2023-09-03 11:47 UTC, LandyHsiao commented on pages/beauty_awards.html
> +            <img src="../assets/image/beauty-awards/beauty-awards-6.png" alt="" class="card__item__img mb-2">
從這裡開始img alt text就沒寫了

2023-09-03 11:47 UTC, LandyHsiao commented on pages/beauty_awards.html
> +        <div class="col-lg-4 col-md-6 col-sm-12 mb-md-8 mb-4 d-flex flex-column">
所有col都被加了多餘的`d-flex`跟`flex-column`

2023-09-03 12:30 UTC, cestJessie commented on assets/image/beauty-awards/2023SS.png
已修改

2023-09-03 12:35 UTC, cestJessie commented on pages/beauty_awards.html
> +            <p class="lh-base mb-0 text-justify flex-grow-1 text-Gray-01 link-Gray-02 fs-md-6 fs-7">皇家蜂王乳雙導精華</p>
已修改

2023-09-03 12:37 UTC, cestJessie commented on pages/beauty_awards.html
> +            <img src="../assets/image/beauty-awards/beauty-awards-6.png" alt="" class="card__item__img mb-2">
已修改

2023-09-03 12:39 UTC, cestJessie commented on pages/beauty_awards.html
> +        <div class="col-lg-4 col-md-6 col-sm-12 mb-md-8 mb-4 d-flex flex-column">
已修改

2023-09-03 15:25 UTC, cestJessie commented on assets/scss/pages/_beauty_awards.scss
> +  color: $gradient-02;
已修改

2023-09-03 15:26 UTC, cestJessie commented on pages/beauty_awards.html
已全部修改

2023-09-04 13:23 UTC, LandyHsiao requested changes

2023-09-04 13:23 UTC, LandyHsiao commented on assets/scss/pages/_beauty_awards.scss
> +  font-family: $display-font-family;
品牌字體錯誤

2023-09-04 13:23 UTC, LandyHsiao commented on pages/beauty_awards.html
> +                  <h5 class="card-title product-card__name fs-md-5 fs-6 mb-4">塑妍逆引鑽白菁萃</h5>
不知為何gap不一樣
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/74b094a4-44cd-4cee-8cf0-9c718d8b114d)

2023-09-04 14:44 UTC, LandyHsiao approved these changes

2023-09-06 03:26 UTC, merged