Feature/member edit page
LandyHsiao/beauty-hub pull request #53
Opened 2023-09-09 10:24 UTC by ann328

add member_edit_page.html and member_page.html

2023-09-09 17:25 UTC, LandyHsiao requested changes

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                <a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#CommentEdit" class="ms-2 pe-auto"><i
1. 我的評論以線稿圖來說似乎不能編輯
但似乎可以展開編輯也不錯，所以我覺得可以保留
2. `style="cursor: pointer;"`為何要用這個行內css呢？

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                                <p
所有評論相關的卡片， card-text區塊都會隨著文字多寡改變高度，建議讓他們高度可以一致，比較美觀也較符合設計稿

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                                <p
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/cea13e6c-4632-4594-b4da-970efaac55a2)

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                    <div class="modal fade" id="CareProducts-edit" tabindex="-1" aria-labelledby="exampleModalLabel"
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/de6688e9-9adc-4ba1-a4ea-801f19584991)
所有modal在較寬螢幕下都有這問題
modal header裡的東西，寬螢幕下滿版讓title跟close button散到最旁邊超難閱讀建議，建議也包一層container變成這種感覺↓
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/44023765-b9aa-4ec4-ade2-08874d3633cc)

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                    <div class="modal fade" id="CareProducts-edit" tabindex="-1" aria-labelledby="exampleModalLabel"
另外需注意aria-labelledby等相關aria-XXX的正確用法 [可參考這篇文章](https://noiseyou99.medium.com/%E4%BD%BF%E7%94%A8aria-%E6%A8%99%E7%B1%A4%E5%81%9Aaccessibility-1e306099ddc4)
不然不如就別寫了，反而是錯的

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                <div class="swiper-button-prev-CareProducts-d">
你把`swiper-button-prev`這個class拿掉會讓當已經沒有前一頁的時候把此button disabled掉的效果消失，我覺得有點影響UX
同理`swiper-button-next`也一樣
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/ff5b69b9-a482-4ed3-b535-de2118fe5cfe)

2023-09-09 17:25 UTC, LandyHsiao commented on layout/member_page.ejs
> +                slidesPerView: 1,
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/a0196009-74ce-4db9-9962-22a187d70c17)
多數swiper在小螢幕下因為隱藏了navigation button所以看不出來可以左右滑動
我覺得改成slidesPerView 1.5 UX會比較好但相對沒那麼美觀，可以考慮看看要著重哪方面

2023-09-09 17:25 UTC, LandyHsiao commented on layout/member_page.ejs
> +        slidesPerView: 3,
跟BS一樣，既然你有用breakpoint去做slidesPerview的down to topRWD，那你這這裡設定3的話會讓375px以下的螢幕slidesPerView變成3喔
正確作法是這裡設成最小的1，breakpoints裡面再去設XXXpx以上slidesPerView要改成多少

2023-09-09 17:25 UTC, LandyHsiao commented on layout/member_page.ejs
> +        slidesPerView: 3,
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/aa0007df-7e44-49cb-b74b-7091a4dd9bac)
稀有ㄉ螢幕小於375px於是受害的galaxy fold
[官方文件教學可以參考這裡](https://swiperjs.com/swiper-api#param-breakpoints)

2023-09-09 17:25 UTC, LandyHsiao commented on pages/member_page.html
> +                                <p
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/993bfce1-34c8-47c0-a115-33a01cc0bf20)
美觀上考量會建議上圖兩個區塊要處理在較小螢幕時圖片長寬比問題
但這純粹美觀問題，沒空可以不用改

2023-09-10 09:59 UTC, ann328 commented on pages/member_page.html
> +                <a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#CommentEdit" class="ms-2 pe-auto"><i
被前面的展開影響，所以後續都有用，那我修改～

2023-09-11 15:12 UTC, LandyHsiao approved these changes

2023-09-11 15:12 UTC, merged