Feature/more products
LandyHsiao/beauty-hub pull request #57
Opened 2023-09-10 12:23 UTC by LandyHsiao

product page量產了02～06(對應首頁熱門排行榜保養品與底妝的前三名)、16～18(首頁好評推推的前三個)
順便修正了product page以下問題：
1. pagination應該在評論有三篇時才會顯示
2. 化學成分外連到cosdna時改用`_blank`
3. 將「我的頭像」改為梅子綠以符合線稿圖情境

**因安正在利用gh-page問助教問題故沒有deploy過**

2023-09-11 11:46 UTC, cestJessie commented on pages/product_03.html
1. product_03產品圖在hover時似乎會被裁切掉
2. 文字介紹建議使用左右對齊，畫面看起來較整齊

2023-09-11 11:49 UTC, cestJessie commented on pages/product_04.html
product_04、product_05產品圖在hover時prodcut-intro__logo-wrap似乎會縮放

2023-09-11 11:54 UTC, cestJessie requested changes

2023-09-11 11:54 UTC, cestJessie commented on pages/product_03.html
1. product_03產品圖在hover時似乎會被裁切掉
2. 文字介紹建議使用左右對齊，畫面看起來較整齊

2023-09-11 11:54 UTC, cestJessie commented on pages/product_04.html
product_04、product_05產品圖在hover時prodcut-intro__logo-wrap似乎會縮放

2023-09-11 15:24 UTC, LandyHsiao commented on pages/product_03.html
會被裁掉是正確的效果欸，不然hover放大會變成這樣喔↓
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/2471447c-e493-4edd-8b20-de7745d81278)

2023-09-11 15:43 UTC, LandyHsiao commented on pages/product_04.html
`prodcut-intro__logo-wrap`沒有縮放，經檢查是圖片左右兩側有不明透明像素，導致乍看的圖片寬度跟實際圖片寬度不同，進而影響視覺上hover放大跟object-fit效果造成的
目前更換左右沒有多餘空白像素的圖片就改善了
目前替換掉的兩張圖片等此PR通過後會再開hotfix branch改掉首頁的圖片

2023-09-11 15:45 UTC, LandyHsiao commented on pages/product_04.html
圖片兩側的多餘透明像素↓
![image](https://github.com/LandyHsiao/beauty-hub/assets/102709032/0bd55637-3ab8-49cd-9f9d-c5132af7de23)

2023-09-12 09:56 UTC, cestJessie approved these changes

2023-09-12 09:57 UTC, merged